# Generated by Django 3.2.16 on 2022-11-23 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_pagamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_agendada',
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
        migrations.AlterField(
            model_name='commentcliente',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='commentempresa',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='servico',
            name='hora_agendada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
