# Generated by Django 3.2.16 on 2022-11-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_auto_20221123_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
