# Generated by Django 3.2.16 on 2022-11-25 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_servico_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='orcamento',
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_agendada',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
    ]
