# Generated by Django 3.2.16 on 2022-11-28 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_remove_servico_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cvv',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='num_cartao',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='titular',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='validade',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_agendada',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
    ]
