# Generated by Django 3.2.16 on 2022-11-29 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_auto_20221128_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentcliente',
            old_name='cliente',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='validade',
            field=models.DateField(default=datetime.date(2022, 11, 29)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_agendada',
            field=models.DateField(default=datetime.date(2022, 11, 29)),
        ),
    ]
