# Generated by Django 3.2.16 on 2022-11-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_empresa_cnpj'),
        ('agendamento', '0009_auto_20221129_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa'),
        ),
    ]
