# Generated by Django 3.2.16 on 2022-11-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_empresa',
            new_name='nome_fantasia',
        ),
    ]
