# Generated by Django 3.2.16 on 2022-11-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nome_empresa_empresa_nome_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='empresa',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Empresa'),
        ),
    ]
