# Generated by Django 3.2.16 on 2022-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tags_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='dom',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='qua',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='qui',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sab',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='seg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sex',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
