# Generated by Django 3.2.16 on 2022-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221116_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tags'),
        ),
    ]
